name: PR

on:
  workflow_dispatch:
  pull_request_target:

jobs:
  build-ios:
    name: Build
    uses: ./.github/workflows/build-ios.yml

  build-android:
    name: Build
    uses: ./.github/workflows/build-android.yml

  test-ios-e2e:
    name: Test
    uses: ./.github/workflows/test-ios-e2e.yml
    needs: [build-ios]
    secrets: inherit

  test-android-e2e:
    name: Android - e2e
    needs: [build-android]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-android
        with:
          path: ${{ env.APP_PATH }}
          key: ${{ runner.os }}-${{ hashFiles('src/**', 'android/**', env.EXAMPLE_SRC, env.APP_PATH ) }}

      - uses: mobile-dev-inc/action-maestro-cloud@v1.8.0
        id: upload
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: ${{ env.APP_PATH }}
          include-tags: ${{ inputs.test-tags }}

      # Step can be removed when this is fixed:
      # https://github.com/mobile-dev-inc/action-maestro-cloud/issues/28
      - name: Check for  maestro errors
        run: |
          if [[ "$MAESTRO_CLOUD_FLOW_RESULTS" == *"ERROR"* || "$MAESTRO_CLOUD_FLOW_RESULTS" == *"CANCELED"* ]]; then
            echo "One or more tests failed or were canceled."
            exit 1
          fi
        env:
          MAESTRO_CLOUD_FLOW_RESULTS: ${{ steps.upload.outputs.MAESTRO_CLOUD_FLOW_RESULTS }}

  test-js:
    name: Test
    uses: ./.github/workflows/test-js.yml

  test-android-unit:
    name: Test
    uses: ./.github/workflows/test-android-unit.yml
